### ISSUE TITLE
LGTM.yml to Workflow

### ISSUE THREAD

**Issue by marcogario** [aibaars/codeql#2]
I looked into the lgtm.yml documentation, and picked a few random lgtm.yml files from github (see below). I propose the following template as a starting point for translating an lgtm.yml into an GH actions workflow.

`lgtm.yml`:

```yaml            
extraction:
  cpp:
    prepare:    # Customizable step used by all languages.
      packages:
        - g++-6
    after_prepare:    # Customizable step used by all languages.
      - export GNU_MAKE=make
      - export GIT=true
    configure:    # Customizable step used only by C/C++ extraction.
      command:
        - ./prepare_deps
    before_index:    # Customizable step used by all languages.
      - export BOOST_DIR=$LGTM_SRC/boost
      - export GTEST_DIR=$LGTM_SRC/googletest
      - export HUNSPELL_DIR=$LGTM_SRC/hunspell
      - export CRYPTOPP_DIR=$LGTM_SRC/cryptopp
    index:    # Customizable step used by all languages.
      build_command:
        - $GNU_MAKE -j2 -s 
```

GH actions workflow `lgtm.yml`:
```yaml

name: "LGTM (CPP)"

on: [push]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        # TBC: Only ubuntu support for LGTM
        os: [ubuntu-latest]

    runs-on: ${{ matrix.os }}

    # Prepare TBC: What is the proper action here?
    # packages:
    #   - g++-6

    - name: After Prepare
      run: |
        export GNU_MAKE=make
        export GIT=true
     
    - name: Configure
      run: ./prepare_deps

    - name: Before Index
      run: |
        export BOOST_DIR=$LGTM_SRC/boost
        export GTEST_DIR=$LGTM_SRC/googletest
        export HUNSPELL_DIR=$LGTM_SRC/hunspell
        export CRYPTOPP_DIR=$LGTM_SRC/cryptopp

    # Setup CodeQL
    - uses: ./codeql/init
      with: 
        tools: ${{ secrets.CODEQL_CLI_URL }} # TBC: This should not be needed
        language: cpp

    - name: Build
      run: $GNU_MAKE -j2 -s

    # Finalize
    - uses: ./codeql/finish
```
@anaarmas  Does this resemble what you had in mind? 
Is there any specific project with a lgtm.yml that you think would be a good example and/or expose other usages?

**Open Issues**:
* Only support Ubuntu?
* index/filters: Defines which files NOT to consider. It seems to be only defined in interpreted languages. How to specify in codeQL CLI?
* prepare/packages: Defines dependencies to install. I am sure there is a proper action for this, and we should use it.
* index/build_command: Command to run for the build. In many cases, this is simply the command we run at the end of the workflow, however, note that for C# we only specify the 'solution', thus there might be some language specific features to consider.
* queries: describe specific queries to include/exclude. Not sure how to do this in the codeQL CLI if using a query pack.

----
https://github.com/brettz9/typeson-registry-sca-reverter/blob/master/lgtm.yml
```yaml
extraction:
  javascript:
    index:
      filters:
        - exclude: "dist"
```

https://github.com/sj/hack23-cia-copy/blob/master/lgtm.yml
```yaml
extraction:
  java:
    prepare:
      packages:
        - graphviz
    index:
      build_command: mvn clean package -f "pom.xml" -B -e -Dfindbugs.skip -Dcheckstyle.skip -Dpmd.skip=true -Denforcer.skip -Dmaven.javadoc.skip -DskipTests -Dmaven.test.skip.exec -t /opt/work/.m2/toolchains.xml -pl '!cia-dist-deb,!cia-dist-cloudformation'
```

https://github.com/sj/hack23-cia-copy/blob/master/lgtm.yml
```yaml
extraction:
  cpp:
     configure:
        command:
        - ./autogen.sh
        - ./configure
```

https://github.com/airbreather/Cursively/blob/master/lgtm.yml
```yaml
extraction:
  csharp:
    after_prepare:
      - export LGTM=true
    index:
      solution: src/Cursively/Cursively.csproj
```

https://github.com/scikit-learn/scikit-learn
```yaml
extraction:
  cpp:
    before_index:
      - pip3 install numpy==1.16.3
      - pip3 install --no-deps scipy Cython
    index:
      build_command:
        - python3 setup.py build_ext -i
```

**Comment by anaarmas** [comment]
Nice! This is indeed the kind of conversion I had in mind :D

> Only support Ubuntu?
 I think we should only include ubuntu in the list of os we generate, since that's what LGTM.com offers. But I think the generated workflow could contain lots of comments indicating how it can be extended, for example in that line saying that other os values can be added to the list.

Regarding the kind of workflow we generate, I had thought we'd generate a standalone workflow, i.e. the kind I'm working on (see https://github.com/aibaars/codeql/blob/separate_workflow/.github/workflows/end-to-end-amazon-cognito-js.yml) - as opposed to the kind Arthur is working on which is meant more for repos that already have a CI workflow and want to include the codeql analysis within their existing workflow by adding a few lines. Maybe @aibaars has a different opinion about this.

**Comment by marcogario** [comment]
This is what I am currently generating:
```yaml

# WARNING: Section 'path_classifier' not supported
# WARNING: Section 'queries' not supported
# WARNING: Language specific index instructions not implemented.
name: "CodeQL Workflow (generated from lgtm.yaml)"
"on":
- "push"
- "pull_request"
jobs:
  codeQL-cpp:
    name: "codeQL-cpp"
    runs-on: "ubuntu-latest"
    steps:
    - uses: "actions/checkout@v1"
    - name: "Prepare"
      run: "sudo apt install -y g++-6"
    - name: "Configure"
      run: "./prepare_deps"
    - name: "analysis"
      uses: "./codeql-self-contained"
      with:
        language: "cpp"
        tools: "${{ secrets.CODEQL_URL }}"
        license: "${{ secrets.CODEQL_LICENSE_URL }}"
        build: "$GNU_MAKE -j2 -s"
    strategy:
      fail-fast: false
```

Notice:
1. We are not using a build-matrix since we are building only on Ubuntu. This can be setup as a matrix, but it seems more confusing for somebody new to Actions.
2. I would probably skip the strategy section (and enable fail-fast).
3. We build a **job** per language if multiple languages are defined in the lgtm.yml. 
4. All language specific options are still not implemented.
5. I think it makes sense to enable this also on PRs by default, since master+branch might yield different results than branch.
6. `on` is a keyword in many YAML implementations, and therefore must be quoted to prevent evaluation to true... I do not find this in the spec, so I might reformat the output of the printer to remove the quoting (that honestly looks ugly).
